### ISSUE TITLE
Python 3 compatibility issue

### ISSUE THREAD

**Issue by sejgit** [OutsourcedGuru/OctoPrint-GitFiles#10]
When I go into your files is shows as being Python 3 compatible but the OctoPrint repository lists it as < 3 compatible.  Unfortunately that means with any normal install method Octoprint python3 ignores it.  Do you need to update the central server in some way.  I know nothing of the plug-in registry.  I use your plugin in my normal work-flow and want to continue with it.  Appreciate you writing it!

**Comment by mhughes2k** [comment]
There seems to be a 2nd issue with this python 3, I found that even with this updated version compatibility I was getting an error in the octoprint log and the plugin was disabled due to an error:

```
2021-02-14 09:42:53,018 - octoprint.plugin.core - WARNING - Plugin GitFiles (1.1.5) can't be compiled under Python 3.7.3 due to invalid syntax
2021-02-14 09:42:53,103 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2021-02-14 09:42:53,197 - octoprint.plugin.core - ERROR - Invalid syntax in /home/pi/oprint/lib/python3.7/site-packages/octoprint_gitfiles/__init__.py for plugin gitfiles
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 762, in _parse_metadata
    root = ast.parse(f.read(), filename=path)
  File "/usr/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_gitfiles/__init__.py", line 79
    os.mkdir(gitfilesFolder, 0755)
```
